module.exports.USER_TYPING = "USER_TYPING";
module.exports.ADD_CARD = "ADD_CARD";
module.exports.ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
module.exports.ADD_CARD_ERROR = "ADD_CARD_ERROR";
module.exports.DELETE_CARD = "DELETE_CARD";
module.exports.DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
module.exports.DELETE_CARD_ERROR = "DELETE_CARD_ERROR";
module.exports.UPDATE_CARD = "UPDATE_CARD";
module.exports.UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
module.exports.UPDATE_CARD_ERROR = "UPDATE_CARD_ERROR";
module.exports.TIMER_BTN_CLICKED = "TIMER_BTN_CLICKED";
module.exports.TIMER_STOPPED = "TIMER_STOPPED";
module.exports.NOT_PRESENT = "NOT_PRESENT";
module.exports.NOT_PRESENT_SUCCESS = "NOT_PRESENT_SUCCESS";
module.exports.NOT_PRESENT_ERROR = "NOT_PRESENT_ERROR";
module.exports.SHARE_CARD = "SHARE_CARD";
module.exports.SHARE_CARD_SUCCESS = "SHARE_CARD_SUCCESS";
module.exports.SHARE_CARD_ERROR = "SHARE_CARD_ERROR";
module.exports.NEXT_FACILITATOR = "NEXT_FACILITATOR";






